### PR TITLE
LPS-76012 add EventDate to event 

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @brianchandotcom, 

could you please publish a snapshot of the artifacts from this repo to the nexus after merging this pull? (or let us know if we can do it on our own)

Thank you!

cc @epgarcia @marcellustavares

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/com-liferay-analytics/compare/04e74c8221...51a0076686

**Comment by brianchandotcom** [comment]
@juliocamarero I published snapshots of all jars in this repo.

**Comment by marcellustavares** [comment]
cc @inacionery

**Comment by juliocamarero** [comment]
@brianchandotcom thank you!! 😗

**Pull request closed without merging**
